image: golang:latest

variables:
  REPO_NAME: gitlab.com/alex-kostirin/chanstego

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - test
    - build

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
      - apt-get update -qq && apt-get install -y -qq libnetfilter-queue-dev
      - go build -o $CI_PROJECT_DIR/client $CI_PROJECT_DIR/examples/client/main.go
      - go build -o $CI_PROJECT_DIR/server $CI_PROJECT_DIR/examples/server/main.go
    artifacts:
      paths:
        - cl
